name: Build and Upload DLL to Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Upload DLL to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: HagglingUI/bin/Release/net9.0/HagglingUI.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
