name: Run HagglingUI Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'HagglingUI/**'
      - 'HagglingUI.Test/**'
      - '.github/workflows/tests.yml'
  pull_request:
    branches: [main]
    paths:
      - 'HagglingUI/**'
      - 'HagglingUI.Test/**'
      - '.github/workflows/tests.yml'

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
      
    - name: Build solution
      run: dotnet build --configuration Release
      
    - name: Run tests
      run: dotnet test HagglingUI.Test/HagglingUI.Test.csproj --configuration Release --no-build --logger "console;verbosity=detailed"